# Generated by Django 5.0.6 on 2025-06-17 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', 'associate_coaches_with_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='suresh.certificate'),
        ),
        migrations.AddField(
            model_name='coach',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coach',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='educations',
            field=models.ManyToManyField(blank=True, to='suresh.education'),
        ),
        migrations.AddField(
            model_name='coach',
            name='functional_skills',
            field=models.ManyToManyField(blank=True, to='suresh.functionalskill'),
        ),
        migrations.AddField(
            model_name='coach',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='honors_awards',
            field=models.ManyToManyField(blank=True, to='suresh.honorsawardspublications'),
        ),
        migrations.AddField(
            model_name='coach',
            name='language_skills',
            field=models.ManyToManyField(blank=True, to='suresh.languageskill'),
        ),
        migrations.AddField(
            model_name='coach',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='technical_skills',
            field=models.ManyToManyField(blank=True, to='suresh.technicalskill'),
        ),
        migrations.AddField(
            model_name='coach',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coach',
            name='work_experiences',
            field=models.ManyToManyField(blank=True, to='suresh.workexperience'),
        ),
    ]
