# Generated by Django 5.0.6 on 2025-05-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('physical', 'Physical Activity'), ('learning', 'Learning'), ('work', 'Work'), ('social', 'Social')], default='physical', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='timesheet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
