# Generated by Django 5.0.6 on 2024-09-10 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0003_remove_customuser_date_joined_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_license', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('institution', models.CharField(max_length=100)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_university', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('area_of_study', models.CharField(max_length=100)),
                ('degree_completed', models.BooleanField(default=False)),
                ('date_completed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('proficiency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HonorsAwardsPublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honor_reward_publication', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('institution', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='honors/')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('speaking_proficiency', models.CharField(max_length=50)),
                ('writing_proficiency', models.CharField(max_length=50)),
                ('reading_proficiency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_responsibilities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('proficiency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('organization_location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_learned', models.DateField()),
                ('challenge_group', models.CharField(max_length=100)),
                ('degree_of_challenge', models.CharField(max_length=50)),
                ('type_of_challenge', models.CharField(max_length=100)),
                ('issuing_authority', models.CharField(max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('religion', models.CharField(max_length=50)),
                ('number_of_children', models.IntegerField()),
                ('occupational_code', models.CharField(max_length=50)),
                ('father_husband_guardian_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('preferred_full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=50)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField()),
                ('birth_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificates', models.ManyToManyField(blank=True, to='suresh.certificate')),
                ('educations', models.ManyToManyField(blank=True, to='suresh.education')),
                ('functional_skills', models.ManyToManyField(blank=True, to='suresh.functionalskill')),
                ('honors_awards_publications', models.ManyToManyField(blank=True, to='suresh.honorsawardspublications')),
                ('language_skills', models.ManyToManyField(blank=True, to='suresh.languageskill')),
                ('previous_experiences', models.ManyToManyField(blank=True, to='suresh.previousexperience')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('technical_skills', models.ManyToManyField(blank=True, to='suresh.technicalskill')),
                ('work_experiences', models.ManyToManyField(blank=True, to='suresh.workexperience')),
            ],
        ),
    ]
