# Generated by Django 5.0.6 on 2024-09-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0004_certificate_education_functionalskill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='professional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences_set', to='suresh.professionalinformation'),
        ),
        migrations.AlterField(
            model_name='professionalinformation',
            name='work_experiences',
            field=models.ManyToManyField(blank=True, related_name='professional_informations', to='suresh.workexperience'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='organization_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
