# Generated by Django 5.0.6 on 2024-09-22 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0005_workexperience_professional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousexperience',
            name='professional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_experience', to='suresh.professionalinformation'),
        ),
        migrations.AlterField(
            model_name='previousexperience',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='previousexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='previousexperience',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
