# Generated by Django 5.0.6 on 2024-09-22 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0006_previousexperience_professional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='professional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations_set', to='suresh.professionalinformation'),
        ),
        migrations.AddField(
            model_name='languageskill',
            name='professional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_skills_set', to='suresh.professionalinformation'),
        ),
    ]
