# Generated by Django 5.0.6 on 2024-09-22 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0007_education_professional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='professional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates_set', to='suresh.professionalinformation'),
        ),
        migrations.AddField(
            model_name='functionalskill',
            name='professional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functional_skills_set', to='suresh.professionalinformation'),
        ),
        migrations.AddField(
            model_name='honorsawardspublications',
            name='professional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honors_awards_set', to='suresh.professionalinformation'),
        ),
        migrations.AddField(
            model_name='technicalskill',
            name='professional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills_set', to='suresh.professionalinformation'),
        ),
        migrations.AlterField(
            model_name='professionalinformation',
            name='work_experiences',
            field=models.ManyToManyField(blank=True, to='suresh.workexperience'),
        ),
    ]
