# Generated by Django 5.0.6 on 2024-09-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0008_certificate_professional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalinformation',
            name='honors_awards_publications',
            field=models.ManyToManyField(blank=True, related_name='professional_informations', to='suresh.honorsawardspublications'),
        ),
        migrations.AlterField(
            model_name='professionalinformation',
            name='work_experiences',
            field=models.ManyToManyField(blank=True, related_name='professional_informations', to='suresh.workexperience'),
        ),
    ]
