# Generated by Django 5.0.6 on 2025-06-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0001_coach_certificates_coach_city_coach_country_and_more'),
        ('suresh', '0010_associate_coaches_with_users'),
    ]

    operations = [
    ]
