# Generated by Django 5.0.6 on 2024-09-22 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0011_workitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwotAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('opportunities', models.TextField(blank=True, null=True)),
                ('threats', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swot_analysis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
