# Generated by Django 5.0.6 on 2025-06-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0011_merge_20250618_0311'),
        ('suresh', '0011_update_coach_model'),
    ]

    operations = [
    ]
