# Generated by Django 5.0.6 on 2025-06-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0012_accomplishment_models'),
        ('suresh', '0012_merge_20250618_0315'),
    ]

    operations = [
    ]
