# Generated by Django 5.0.6 on 2024-09-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0012_swotanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('spiritual', 'Spiritual Goals'), ('fitness', 'Fitness Goals'), ('family', 'Family Goals'), ('career', 'Career Goals'), ('financial', 'Financial Goals'), ('social', 'Social Goals'), ('intellectual', 'Intellectual Goals')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('weightage', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('required_effort', models.FloatField(default=0)),
                ('spent_effort', models.FloatField(default=0)),
                ('coach', models.CharField(blank=True, max_length=255, null=True)),
                ('accomplishment', models.TextField(blank=True, null=True)),
                ('main_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to='suresh.maingoal')),
            ],
        ),
    ]
