# Generated by Django 5.0.6 on 2024-09-22 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0014_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='purchasers',
            field=models.ManyToManyField(blank=True, related_name='purchased_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
