# Generated by Django 5.0.6 on 2024-10-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0019_alter_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swotanalysis',
            name='opportunities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swotanalysis',
            name='strengths',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swotanalysis',
            name='threats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swotanalysis',
            name='weaknesses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
