# Generated by Django 5.0.6 on 2024-10-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0020_alter_swotanalysis_opportunities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swotanalysis',
            name='opportunities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swotanalysis',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swotanalysis',
            name='threats',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swotanalysis',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
