# Generated by Django 5.0.6 on 2024-10-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0021_alter_swotanalysis_opportunities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swotanalysis',
            name='opportunities',
        ),
        migrations.RemoveField(
            model_name='swotanalysis',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='swotanalysis',
            name='threats',
        ),
        migrations.RemoveField(
            model_name='swotanalysis',
            name='weaknesses',
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('swot_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='suresh.swotanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('swot_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strengths', to='suresh.swotanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('swot_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='suresh.swotanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('swot_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='suresh.swotanalysis')),
            ],
        ),
    ]
