# Generated by Django 5.0.6 on 2024-10-25 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0022_remove_swotanalysis_opportunities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swotanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swot_analyses', to=settings.AUTH_USER_MODEL),
        ),
    ]
