# Generated by Django 5.0.6 on 2024-10-25 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0023_alter_swotanalysis_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='swot_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='suresh.swotanalysis'),
        ),
    ]
