# Generated by Django 5.0.6 on 2024-12-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0031_course_discount_end_date_course_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='discount_end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='course',
            name='discount_start_date',
        ),
        migrations.AlterField(
            model_name='videolecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lectures', to='suresh.course'),
        ),
    ]
