# Generated by Django 5.0.6 on 2024-12-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0033_alter_opportunity_swot_analysis_and_more'),
        ('suresh', 'XXXX_update_habit_users'),
    ]

    operations = [
    ]
