# Generated by Django 5.0.6 on 2024-12-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suresh', '0034_merge_20241211_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='reminders',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='time',
        ),
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('health', 'Health & Fitness'), ('learning', 'Learning & Growth'), ('productivity', 'Productivity'), ('mindfulness', 'Mindfulness'), ('social', 'Social & Family'), ('career', 'Career')], max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
